### ISSUE TITLE
Unexpected error encountered during compilation when using @json at the top of the class

### ISSUE THREAD

**Issue by thaitnq13** [JairusSW/json-as#116]
Hello, Nice to meet you,

This is my example 

```typescript
import { JSON } from "json-as";

@json
class User {
  name: string = "Unknown";
  age: i32 = 0;
}
 
class Response {
  message: string = "";
}
 
export function processUser2(userJsonPtr: usize): ArrayBuffer {
  // Decode UTF-8 string from memory
  const userJson = String.UTF8.decodeUnsafe(
    userJsonPtr,
    userJsonPtr + 100,
    true
  );
 
  // Parse JSON using json-as
  if (!userJson) {
    throw new Error("userJson is not defined");
  }
  const user = JSON.parse<User>(userJson);
 
  // Modify object
  const map = new Map<string, string>();
  const message = `Hello, ${user.name}! You are ${user.age + 5} years old.`;
  map.set("message", message);
 
  // Serialize response and encode it into memory
  const responseString = JSON.stringify(map);
  return String.UTF8.encode(responseString, true);
}
``` 

When I run "asc ./assembly/index.ts" --transform json-as/transform --textFile output.wat

I haved encountered with this error

Whoops, the AssemblyScript compiler has crashed during initialize :-(
▌
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌
▌ AssertionError: assertion failed
▌     at Z.assert (\node_modules\assemblyscript\std\portable\index.js:216:11)
▌     at Dn.initialize (\node_modules\assemblyscript\src\program.ts:1178:27)
▌     at Module.P0 (\node_modules\assemblyscript\src\index-wasm.ts:352:11)
▌     at Module.qe (\node_modules\assemblyscript\cli\index.js:714:22)
▌     at async file:////node_modules/assemblyscript/bin/asc.js:33:22
▌
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌
▌ Thank you!

Therefore, I could not parse or stringtify this JSON well
I'm glad if you help me

**Comment by JairusSW** [comment]
Thanks, I'll take a look in a moment

**Comment by thaitnq13** [comment]
Thank you,
This is the debug information

`Created schema: User
Added as-bs import: import {
  bs
} from "json-as\blib\bas-bs"

__SERIALIZE(ptr: usize): void {
  bs.proposeSize(54);
  store<u64>(bs.offset, 27303545189564539, 0); // {"na
  store<u64>(bs.offset, 16325694684725357, 8); // me":
  bs.offset += 16;
  JSON.__serialize<string>(load<string>(ptr, offsetof<this>("name")));
  store<u64>(bs.offset, 28992339215253548, 0); // ,"ag
  store<u32>(bs.offset, 2228325, 8); // e"
  store<u16>(bs.offset, 58, 12); // :
  bs.offset += 14;
  JSON.__serialize<i32>(load<i32>(ptr, offsetof<this>("age")));
  store<u16>(bs.offset, 125, 0); // }
  bs.offset += 2;
}
@inline __INITIALIZE(): this {
  this.name = "Unknown";
  this.age = 0;
  return this;
}
__DESERIALIZE(keyStart: usize, keyEnd: usize, valStart: usize, valEnd: usize, ptr: usize): void {
  switch (<u32>keyEnd - <u32>keyStart) {
    case 6: {
      let code = load<u64>(keyStart) & 0x0000FFFFFFFFFFFF;
      if (code == 433798447201) { // age
        store<i32>(ptr, JSON.__deserialize<i32>(valStart, valEnd, 0), offsetof<this>("age"));
        return;
      }
      return;
    }
    case 8: {
      let code = load<u64>(keyStart);
      if (code == 28429440805568622) { // name
        store<string>(ptr, JSON.__deserialize<string>(valStart, valEnd, 0), offsetof<this>("name"));
        return;
      }
      return;
    }
  }
}
`

▌ Whoops, the AssemblyScript compiler has crashed during initialize :-(
▌
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌
▌ AssertionError: assertion failed
▌     at Z.assert (D:\demo\demo\my-app\node_modules\assemblyscript\std\portable\index.js:216:11)
▌     at Dn.initialize (D:\demo\demo\my-app\node_modules\assemblyscript\src\program.ts:1178:27)
▌     at Module.B0 (D:\demo\demo\my-app\node_modules\assemblyscript\src\index-wasm.ts:352:11)
▌     at Module.qe (D:\demo\demo\my-app\node_modules\assemblyscript\cli\index.js:714:22)
▌     at async file:///D:/demo/demo/my-app/node_modules/assemblyscript/bin/asc.js:33:22
▌
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌
▌ Thank you!

If you need any information, I can provide it for you.

**Comment by JairusSW** [comment]
What I'm seeing here is the import path is wrong.
From the logs, I see that this import is added to the top:
```typescript
Added as-bs import: import {
bs
} from "json-as\blib\bas-bs"
```
The path `"json-as\blib\bas-bs"` is invalid and should instead be `"json-as\lib\as-bs"`, so I'm guessing that what was in the `node_modules` got edited somehow.

Can you try running `npm i json-as@1.0.2 --force` and try again?

**Comment by thaitnq13** [comment]
Hello Mr.Jairus,
Thank you for your recommendation

> I'm assuming your using windows
Yes, I'm using window

> Are you running in portable mode? This might be causing the problems
Sorry, I don't get it. Could you explain more about this?

> Can you put the line import { bs } from "json-as/lib/as-bs" at the top of your file
This may solve this problem.

**Comment by JairusSW** [comment]
@thaitnq13 I think it should be fixed in `json-as@1.0.3`, so if you download that, it *hopefully* should work

**Comment by thaitnq13** [comment]
Hi Mr @JairusSW,

I have updated the version of json-as to 1.0.3, but this problem still remains.

Here is the debug information. I noticed that the import is correct, but the initialization code still crashes.

Created schema: User
Added as-bs import: import {
  bs
} from "../../../lib/as-bs"
 
__SERIALIZE(ptr: usize): void {
  bs.proposeSize(54);
  store<u64>(bs.offset, 27303545189564539, 0); // {"na
  store<u64>(bs.offset, 16325694684725357, 8); // me":
  bs.offset += 16;
  JSON.__serialize<string>(load<string>(ptr, offsetof<this>("name")));
  store<u64>(bs.offset, 28992339215253548, 0); // ,"ag
  store<u32>(bs.offset, 2228325, 8); // e"
  store<u16>(bs.offset, 58, 12); // :
  bs.offset += 14;
  JSON.__serialize<i32>(load<i32>(ptr, offsetof<this>("age")));
  store<u16>(bs.offset, 125, 0); // }
  bs.offset += 2;
}
@inline __INITIALIZE(): this {
  this.name = "";
  this.age = 0;
  return this;
}
__DESERIALIZE(keyStart: usize, keyEnd: usize, valStart: usize, valEnd: usize, ptr: usize): void {
  switch (<u32>keyEnd - <u32>keyStart) {
    case 6: {
      let code = load<u64>(keyStart) & 0x0000FFFFFFFFFFFF;
      if (code == 433798447201) { // age
        store<i32>(ptr, JSON.__deserialize<i32>(valStart, valEnd, 0), offsetof<this>("age"));
        return;
      }
      return;
    }
    case 8: {
      let code = load<u64>(keyStart);
      if (code == 28429440805568622) { // name
        store<string>(ptr, JSON.__deserialize<string>(valStart, valEnd, 0), offsetof<this>("name"));
        return;
      }
      return;
    }
  }
}
 
Created schema: User
__SERIALIZE(ptr: usize): void {
  bs.proposeSize(54);
  store<u64>(bs.offset, 27303545189564539, 0); // {"na
  store<u64>(bs.offset, 16325694684725357, 8); // me":
  bs.offset += 16;
  JSON.__serialize<string>(load<string>(ptr, offsetof<this>("name")));
  store<u64>(bs.offset, 28992339215253548, 0); // ,"ag
  store<u32>(bs.offset, 2228325, 8); // e"
  store<u16>(bs.offset, 58, 12); // :
  bs.offset += 14;
  JSON.__serialize<i32>(load<i32>(ptr, offsetof<this>("age")));
  store<u16>(bs.offset, 125, 0); // }
  bs.offset += 2;
}
@inline __INITIALIZE(): this {
  this.name = "";
  this.age = 0;
  return this;
}
__DESERIALIZE(keyStart: usize, keyEnd: usize, valStart: usize, valEnd: usize, ptr: usize): void {
  switch (<u32>keyEnd - <u32>keyStart) {
    case 6: {
      let code = load<u64>(keyStart) & 0x0000FFFFFFFFFFFF;
      if (code == 433798447201) { // age
        store<i32>(ptr, JSON.__deserialize<i32>(valStart, valEnd, 0), offsetof<this>("age"));
        return;
      }
      return;
    }
    case 8: {
      let code = load<u64>(keyStart);
      if (code == 28429440805568622) { // name
        store<string>(ptr, JSON.__deserialize<string>(valStart, valEnd, 0), offsetof<this>("name"));
        return;
      }
      return;
    }
  }
}
 
 
▌ Whoops, the AssemblyScript compiler has crashed during initialize :-(
▌
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌
▌ AssertionError: assertion failed
▌     at Z.assert (D:\demo\demo\my-app\node_modules\assemblyscript\std\portable\index.js:216:11)
▌     at Dn.initialize (D:\demo\demo\my-app\node_modules\assemblyscript\src\program.ts:1178:27)
▌     at Module.B0 (D:\demo\demo\my-app\node_modules\assemblyscript\src\index-wasm.ts:352:11)
▌     at Module.qe (D:\demo\demo\my-app\node_modules\assemblyscript\cli\index.js:714:22)
▌     at async file:///D:/demo/demo/my-app/node_modules/assemblyscript/bin/asc.js:33:22
▌
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌
▌ Thank you!

Thank you for your help.

**Comment by JairusSW** [comment]
I'm pretty baffled by what's going on... Never seen this before.
Would you mind sending your workspace over? Like put it on github or a .zip since I can't recreate it?

**Comment by anisus** [comment]
I got the same problem when upgrading _json-as_ from v0.9.26 to v1.0.3.
The stack trace returned from AssemblyScript is identical as reported by @thaitnq13 .
I am also using npm and Windows 11.

I have the issue on a public repo. I can reproduce it on another Windows 11 computer by running the following:

```text
git clone https://github.com/mucklet/mucklet-script.git
cd mucklet-script
npm install json-as@latest
npm run build
```

And by the way; thanks for an awesome library!

**Comment by JairusSW** [comment]
@anisus, thanks. I was able to recreate it and will fix it as soon as I'm out of classes today

**Comment by JairusSW** [comment]
@thaitnq13 @anisus, should be fixed in [v1.0.4](https://www.npmjs.com/package/json-as)
