### ISSUE TITLE
customs serialization/deserialization of generic types

### ISSUE THREAD

**Issue by coderSomya** [JairusSW/json-as#126]
I am trying to use a type in my project with generic types and define custom serializer, deserializer for it.
```
@json
class X<T>{
   x: i32 =  0;
   y: i32 =  0;

   constructor(_x: i32, _y:i32){
    this.x  = _x;
    this.y = _y;
   }

@serializer
  serialize(self: X<T>): string {
     return self.x.toString() +":"+ self.y.toString();
  }

   @deserializer
  deserializer<T>(data: string): X<T> {
    const x = JSON.parse<i32>(data.split(":")[0]);
    const y = JSON.parse<i32>(data.split(":")[1]);
    return new X<T>(x,y);
  }

}
```

However, when i try to use this type:
```
let obj = new X<i32>(4,5);
const serialized = JSON.stringify<X<i32>>(obj);
const deserialized = JSON.parse<X<i32>>(serialized);
```
i get the following compilation errors:
```
ERROR TS2558: Expected 1 type arguments, but got 0.
   :
 2 │ const data = this.serialize(changetype<X>(ptr));
   │                                        ~
   └─ in assembly/index.ts(2,44)

ERROR TS2558: Expected 1 type arguments, but got 0.
   :
 2 │ const data = this.serialize(changetype<X>(ptr));
   │                             ~~~~~~~~~~~~~~~~~~
   └─ in assembly/index.ts(2,33)

ERROR TS2558: Expected 1 type arguments, but got 0.
   :
 1 │ __DESERIALIZE_CUSTOM(data: string): X {
   │                                     ~
   └─ in assembly/index.ts(1,39)
```
i believe this has something to do with generic types not being passed to the the type X.

**Comment by JairusSW** [comment]
@coderSomya, thanks for the issue report!

Issues 1 and 2 were on me and are now fixed in https://github.com/JairusSW/json-as/commit/1274c4706132c98ed35b19dacf8058544e6f8082

Taking in the same generic type `T` on both your class (`class X<T> {`) and your method (`deserializer<T>() {`) isn't quite right. You should just rely on the `T` generic defined by the class.

I modified your code a bit, and this works perfectly on my end.

```js
@json
class X<T> {
  x: i32 = 0;
  y: i32 = 0;

  constructor(_x: i32, _y: i32) {
    this.x = _x;
    this.y = _y;
  }

  @serializer
  serialize(): string {
    return this.x.toString() + ":" + this.y.toString();
  }

  @deserializer
  deserializer(data: string): X<T> {
    const x = JSON.parse<i32>(data.split(":")[0]);
    const y = JSON.parse<i32>(data.split(":")[1]);
    return new X<T>(x, y);
  }

}

let obj = new X<i32>(4, 5);
const serialized = JSON.stringify<X<i32>>(obj);
console.log("Serialized: " + serialized);
const deserialized = JSON.parse<X<i32>>(serialized);
console.log("Deserialized: " + JSON.stringify(deserialized));
```

Hope this helps :)
- @JairusSW

**Comment by coderSomya** [comment]
thanks for the quick fix @JairusSW . appreciate it :)

**Comment by coderSomya** [comment]
i feel there is still an issue though. have a look at this example:
```
@json
class Option<T> {
  has_value: bool = false;
  value: Box<T> | null = null;

  static Some<T>(value: T): Option<T> {
    const option = new Option<T>()
    option.value = new Box<T>(value)
    option.has_value = true
    return option
  }

  static None<T>(): Option<T> {
    return new Option<T>()
  }

  @serializer
  serialize(): string {
    if(this.has_value){
        return JSON.stringify(this.value!.value);
    }
    else return "null";
  }


  @deserializer
  deserializer(data: string): Option<T> {
     if (data === "null") {
      return Option.None<T>();
    } else {
      const value = JSON.parse<T>(data);
      return Option.Some(value)
    }
  }
}
```
```
@json
class args_with_option{
  x: Option<string>

  constructor(_x: Option<string>){
    this.x = _x;
  }
}
```
```
 const opt1 = Option.Some<string>("hello");
 const arg1 = new args_with_option(opt1);

const serialized = JSON.stringify<args_with_option>(arg1);
```

here arg1 is a class with an option field. when i build this, i face this error:
```
ERROR TS2554: Expected 0 arguments, but got 1.
     :
 555 │ return src.__SERIALIZE_CUSTOM(changetype<usize>(src));
     │        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     └─ in ~lib/json-as/assembly/index.ts(555,14)
```

am i doing something wrong?

**Comment by JairusSW** [comment]
@coderSomya, that's my bad. I forgot to update that and it was fixed in #128
The fix is published on NPM as [v1.0.7](https://www.npmjs.com/package/json-as/v/1.0.7)
